global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'feature-serving'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
  - job_name: 'flink'
    static_configs:
      - targets: ['jobmanager:9250', 'taskmanager:9250']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
