global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flink'
    static_configs:
      - targets: ['jobmanager:9250', 'taskmanager:9250'] # Flink metrics (requires config)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
